### ISSUE TITLE
Some fonts takes a very long time to load

### ISSUE THREAD

**Issue by mindeunix** [Elv13/awesome-1#11]
I do not know where I should write about this, I just wonder why such a big difference between different fonts, as an example I have two textbox widgets with different fonts:
```lua
        benchmark("font 1")
        local w1 =  wibox.widget.textbox("test 1")
        w1.font = "LED_mono 8"
        top_layout_sys:add(w1)
        benchmark("font 1")

        benchmark("font 2")
        local w2 =  wibox.widget.textbox("test 2")
        w2.font = "Sans 8"
        top_layout_sys:add(w2)
        benchmark("font 2")
```
(benchmark is just a sample function to calculate how long it takes to create these widgets) and I'm getting really surprising results:

![b](https://i.imgur.com/ruf9kEf.png])

I tried different fonts, for example Unifont (12M) which is larger then LED_mono (2.8K) and it still loads faster. Why there is such a big difference?

**Comment by psychon** [comment]
...why is this reported here?

**Comment by mindeunix** [comment]
@psychon ...why is this reported here?

I just asked, this is not a BUG report.

**Comment by psychon** [comment]
Ok, well: I guess your benchmark is wrong. I bet there is some caching somewhere and so only the first thing actually does something. Besides that: No idea what could be going on.

**Comment by mindeunix** [comment]
It does not matter which font will be first, LED_mono still loads much slower.

```lua
        local w0 =  wibox.widget.textbox("test")
        top_layout_sys:add(w0)

        benchmark("font 1")
        local w1 =  wibox.widget.textbox("test 1")
        w1.font = "Arial 10"
        top_layout_sys:add(w1)
        benchmark("font 1")

        benchmark("font 2")
        local w2 =  wibox.widget.textbox("test 2")
        w2.font = "Sans 10"
        top_layout_sys:add(w2)
        benchmark("font 2")

        benchmark("font 3")
        local w3 =  wibox.widget.textbox("test 3")
        w3.font = "LED_mono 10"
        top_layout_sys:add(w3)
        benchmark("font 3")
```

![](http://i.imgur.com/K2BlSm2.png)
